# I had to imploy this strategy of cloudbuild because work computer I'm coding on doesn't have
# access to docker command. You can safely delete this and use
# docker build -t gcr.io/<your_project_id>/my-backend .
# docker push gcr.io/<your_project_id>/my-backend
# before each deploy. You will also need to update the deploy-gcp github action pipelines to
# use Dockerfile instead of cloudbuild.yaml

steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    dir: "/workspace/backend" # Set the working directory for the npm step
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io$_PROJECT_ID/$_BACKEND_INSTANCE_NAME", "."]
    dir: "/workspace/backend"
images:
  - "gcr.io/$_PROJECT_ID/$_BACKEND_INSTANCE_NAME"
