name: AI Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  code-review:
    # Optional; to run only when a label is attached. Doesn't really work cause GPT can only review one commit at a time and adding the label counts as a commit maybe.
    if: ${{ contains(github.event.*.labels.*.name, 'gpt review') }}
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          LANGUAGE: English
          # Play with these to get desired randomness. Ask chatGPT for explinations if you don't know what they do
          MODEL: gpt-4
          top_p: .9
          temperature: .9
